development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: smart_ac_development
  pool:     5
  username: richardson
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: smart_ac_test
  pool:     5
  username: richardson
  password:
  template: template0

production:
  url: <%= ENV['DATABASE_URL'] %>